services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=example-key
    depends_on:
      - backend
    networks:
      - learn-x-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUPABASE_URL=https://example.supabase.co
      - SUPABASE_SERVICE_KEY=example-service-key
      - JWT_SECRET=example-jwt-secret
      - OPENAI_API_KEY=example-openai-key
      - ANTHROPIC_API_KEY=example-anthropic-key
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - learn-x-network
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUPABASE_URL=https://example.supabase.co
      - SUPABASE_SERVICE_KEY=example-service-key
      - JWT_SECRET=example-jwt-secret
      - OPENAI_API_KEY=example-openai-key
      - ANTHROPIC_API_KEY=example-anthropic-key
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    networks:
      - learn-x-network
    depends_on:
      - redis
    command: npm run start:worker

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - learn-x-network

networks:
  learn-x-network:
    driver: bridge

volumes:
  redis-data: