services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
    networks:
      - learn-x-network
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
    networks:
      - learn-x-network
    depends_on:
      - redis
    command: npm run start:worker

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - learn-x-network

networks:
  learn-x-network:
    driver: bridge

volumes:
  redis-data: