# Enhanced PGMQ Docker Compose Configuration
# Separates API server from workers for better reliability
version: '3.8'

services:
  # API Server (no workers)
  api:
    build: .
    command: ["node", "dist/api-server.js"]
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Enhanced PGMQ Worker (separate container)
  pgmq-worker:
    build: .
    command: ["node", "dist/workers/enhanced-pgmq-worker.js"]
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKER_ID=pgmq-worker-${HOSTNAME}
    restart: always
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Scale workers for high load
  pgmq-worker-2:
    build: .
    command: ["node", "dist/workers/enhanced-pgmq-worker.js"]
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKER_ID=pgmq-worker-2-${HOSTNAME}
    restart: always
    depends_on:
      - api
    profiles:
      - scaling  # Only start with: docker-compose --profile scaling up
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  # No Redis needed - everything is in PostgreSQL!
  
networks:
  default:
    name: learn-x-enhanced